### ISSUE TITLE
what is this file used for?

### ISSUE THREAD

**Issue by goern** [thoth-station/elyra-aidevsecops-tutorial#126]
Why do we have this file?
https://github.com/thoth-station/elyra-aidevsecops-tutorial/blob/6e35b3ec4b589ede30e06fa22a0529fc99044b83/Pipfile#L1

/kind questions
/sig docs
/assign @pacospace

**Comment by pacospace** [comment]
There are all dev packages in that Pipfile, so if someone wants to work on that from local machine it needs to use that and it contains all dependencies in that case.

**Comment by goern** [comment]
So its basically to stay backward-compatible with `pipenv`, IIRC we don't need this 'root-level Pipfile' if we use `thamos`, right?!

@fridex could you point to the corresponding thanos doc?

**Comment by fridex** [comment]
> So its basically to stay backward-compatible with `pipenv`, IIRC we don't need this 'root-level Pipfile' if we use `thamos`, right?!
> 
> @fridex could you point to the corresponding thanos doc?

We don't have an entry in docs for this. Running `thamos check` should warn about this type of configuration:

https://github.com/thoth-station/thamos/blob/dd50f2a2ba76a3257220ae665614108c07c84c50/thamos/config.py#L631-L638

**Comment by goern** [comment]
@pacospace is there a section in the tutorial about this behaviour/intention?

**Comment by pacospace** [comment]
> @pacospace is there a section in the tutorial about this behaviour/intention?

No there is no mention about this behaviour, but my understanding was that either one solution or the other should be present. So the one in root should be removed.

But what about dev packages? should be another overlay `dev`?

**Comment by fridex** [comment]
> But what about dev packages? should be another overlay `dev`?

Yes, I think they can form "dev" environment, hence `dev` overlay could be considered.

**Comment by goern** [comment]
> > But what about dev packages? should be another overlay `dev`?
> 
> Yes, I think they can form "dev" environment, hence `dev` overlay could be considered.

or 'laptop' or 'local' or ...
