### ISSUE TITLE
First Tutorial Step, pre-requisites is miss-numbered and not linked in JupyterBook

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/elyra-aidevsecops-tutorial#269]
![image](https://user-images.githubusercontent.com/4494906/131146604-87eb4afd-3148-470f-9479-050b779ace40.png)

Need to update the jupyter book config or toc file to ensure the link a numbering are correct in the Jupyterbook. It looks to work fine in the [README.md](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/README.md#tutorial-steps) this page is rendered from.

**Comment by goern** [comment]
/kind feature
/priority critical-urgent

still active?
