### ISSUE TITLE
patch image tag fails

### ISSUE THREAD

**Issue by pacospace** [thoth-station/elyra-aidevsecops-tutorial#38]
**Describe the bug**
patch image tag fails https://github.com/thoth-station/elyra-aidevsecops-tutorial/blob/51b4b15062a3aaaa5d82c21eaf5e7639d2066f5d/.aicoe-ci.yaml#L15

**To Reproduce**
1. Retrigger pipeline

**Expected behavior**
Correct patch image tag in context path `elyra-aidevsecops-tutorial/manifests/overlays/test/imagestreamtag.yaml`

**Screenshots**
```
+ '[' -z elyra-aidevsecops-tutorial ]
+ registry_repo=elyra-aidevsecops-tutorial
+ '[' -z elyra-aidevsecops-tutorial/manifests/overlays/test/imagestreamtag.yaml ]
+ contextpath=elyra-aidevsecops-tutorial/manifests/overlays/test/imagestreamtag.yaml
+ '[' '!' -z elyra-aidevsecops-tutorial ]
+ yq r '-d*' elyra-aidevsecops-tutorial/manifests/overlays/test/imagestreamtag.yaml metadata.name
13:54:30 main [ERRO] open elyra-aidevsecops-tutorial/manifests/overlays/test/imagestreamtag.yaml: no such file or directory
+ docs='Error: open elyra-aidevsecops-tutorial/manifests/overlays/test/imagestreamtag.yaml: no such file or directory
Usage:
  yq read [yaml_file] [path_expression] [flags]
```
**Additional context**

Reference: https://tekton-dashboard-openshift-pipelines.apps.ocp4.prod.psi.redhat.com/#/namespaces/aicoe-infra-prod/pipelineruns/tag-release-hdf4n

**Comment by harshad16** [comment]
the path should be changed to : `manifests/overlays/test`
