### ISSUE TITLE
Browser stuck when running locally.

### ISSUE THREAD

**Issue by martinpovolny** [thoth-station/elyra-aidevsecops-tutorial#45]
Just linking this issue here, so that people do not wonder where's the problem:

https://github.com/opendatahub-io/s2i-lab-elyra/issues/9

Happens to me with 0.0.4 or 0.0.5 (quay.io/thoth-station/s2i-lab-elyra:v0.0.5).

**Comment by pacospace** [comment]
> Just linking this issue here, so that people do not wonder where's the problem:
> 
> [opendatahub-io/s2i-lab-elyra#9](https://github.com/opendatahub-io/s2i-lab-elyra/issues/9)
> 
> Happens to me with 0.0.4 or 0.0.5 (quay.io/thoth-station/s2i-lab-elyra:v0.0.5).

I removed it in the new doc, so I point directly on the use of operate first :)

**Comment by pacospace** [comment]
This is solved by new `jupyterlab-requirements version >= 0.6.4`
